"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-07-30 11:57:14.539150
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("workspace_path", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("reference_asset_id", sa.String(length=36), nullable=False),
        sa.Column("source_width", sa.Integer(), nullable=False),
        sa.Column("source_height", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("source_width > 0 AND source_height > 0", name="ck_profile_source_size"),
        sa.CheckConstraint("version >= 1", name="ck_profile_version"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_game_profiles_name"),
    )
    op.create_index(
        op.f("ix_game_profiles_project_id"), "game_profiles", ["project_id"], unique=False
    )
    op.create_table(
        "video_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("local_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("duration_ms > 0", name="ck_video_duration"),
        sa.CheckConstraint("size_bytes > 0", name="ck_video_size"),
        sa.CheckConstraint("width > 0 AND height > 0", name="ck_video_dimensions"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_video_assets_project_id"), "video_assets", ["project_id"], unique=False
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("kind IN ('character','game')", name="ck_category_kind"),
        sa.ForeignKeyConstraint(["profile_id"], ["game_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "name", name="uq_categories_profile_name"),
    )
    op.create_index(op.f("ix_categories_profile_id"), "categories", ["profile_id"], unique=False)
    op.create_table(
        "hud_regions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("width > 0 AND height > 0", name="ck_hud_region_size"),
        sa.CheckConstraint("x >= 0 AND y >= 0", name="ck_hud_region_origin"),
        sa.ForeignKeyConstraint(["profile_id"], ["game_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "name", name="uq_hud_regions_profile_name"),
    )
    op.create_index(op.f("ix_hud_regions_profile_id"), "hud_regions", ["profile_id"], unique=False)
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("interval_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("total_frames", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued','running','paused','review_ready','completed','failed',"
            "'cancelled')",
            name="ck_pipeline_status",
        ),
        sa.CheckConstraint("attempt >= 1", name="ck_pipeline_attempt"),
        sa.CheckConstraint("interval_ms > 0", name="ck_pipeline_interval"),
        sa.CheckConstraint("total_frames >= 0", name="ck_pipeline_total_frames"),
        sa.CheckConstraint("version >= 1", name="ck_pipeline_version"),
        sa.ForeignKeyConstraint(["profile_id"], ["game_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["video_id"], ["video_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_runs_profile_id"), "pipeline_runs", ["profile_id"], unique=False
    )
    op.create_index(op.f("ix_pipeline_runs_video_id"), "pipeline_runs", ["video_id"], unique=False)
    op.create_table(
        "exports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("output_relpath", sa.Text(), nullable=True),
        sa.Column("input_revision", sa.Integer(), nullable=False),
        sa.Column("manifest_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued','running','completed','failed')", name="ck_export_status"
        ),
        sa.CheckConstraint("input_revision >= 0", name="ck_export_revision"),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exports_run_id"), "exports", ["run_id"], unique=False)
    op.create_table(
        "frames",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("timestamp_ms", sa.Integer(), nullable=False),
        sa.Column("image_relpath", sa.Text(), nullable=False),
        sa.Column("stage_status", sa.String(length=30), nullable=False),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "review_status IN ('pending','accepted','rejected')", name="ck_frame_review_status"
        ),
        sa.CheckConstraint(
            "stage_status IN ('pending','sampled','cropped','ocr_complete','review_pending')",
            name="ck_frame_stage_status",
        ),
        sa.CheckConstraint("frame_index >= 0 AND timestamp_ms >= 0", name="ck_frame_position"),
        sa.CheckConstraint("version >= 1", name="ck_frame_version"),
        sa.CheckConstraint("width > 0 AND height > 0", name="ck_frame_dimensions"),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "frame_index", name="uq_frames_run_index"),
    )
    op.create_index(op.f("ix_frames_run_id"), "frames", ["run_id"], unique=False)
    op.create_table(
        "stage_checkpoints",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("artifact_relpath", sa.Text(), nullable=True),
        sa.Column("artifact_hash", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','running','completed','failed')", name="ck_checkpoint_status"
        ),
        sa.CheckConstraint("frame_index >= 0 AND attempt >= 1", name="ck_checkpoint_position"),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "frame_index", "stage"),
        sa.UniqueConstraint("run_id", "frame_index", "stage", name="uq_stage_checkpoint"),
    )
    op.create_table(
        "region_samples",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("frame_id", sa.String(length=36), nullable=False),
        sa.Column("region_id", sa.String(length=36), nullable=False),
        sa.Column("crop_relpath", sa.Text(), nullable=False),
        sa.Column("stage_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "stage_status IN ('pending','cropped','ocr_complete','failed')",
            name="ck_region_sample_stage_status",
        ),
        sa.ForeignKeyConstraint(["frame_id"], ["frames.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["region_id"], ["hud_regions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("frame_id", "region_id", name="uq_region_samples_frame_region"),
    )
    op.create_index(
        op.f("ix_region_samples_frame_id"), "region_samples", ["frame_id"], unique=False
    )
    op.create_index(
        op.f("ix_region_samples_region_id"), "region_samples", ["region_id"], unique=False
    )
    op.create_table(
        "ocr_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sample_id", sa.String(length=36), nullable=False),
        sa.Column("char", sa.String(length=16), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("engine", sa.String(length=100), nullable=False),
        sa.Column("engine_version", sa.String(length=100), nullable=False),
        sa.Column("config_hash", sa.String(length=128), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("rejection_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_ocr_confidence"),
        sa.CheckConstraint("width > 0 AND height > 0", name="ck_ocr_size"),
        sa.CheckConstraint("x >= 0 AND y >= 0", name="ck_ocr_origin"),
        sa.ForeignKeyConstraint(["sample_id"], ["region_samples.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ocr_observations_sample_id"), "ocr_observations", ["sample_id"], unique=False
    )
    op.create_table(
        "annotations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("frame_id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("observation_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("source IN ('ocr','manual')", name="ck_annotation_source"),
        sa.CheckConstraint(
            "status IN ('proposed','accepted','deleted')", name="ck_annotation_status"
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_annotation_confidence",
        ),
        sa.CheckConstraint("version >= 1", name="ck_annotation_version"),
        sa.CheckConstraint("width > 0 AND height > 0", name="ck_annotation_size"),
        sa.CheckConstraint("x >= 0 AND y >= 0", name="ck_annotation_origin"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["frame_id"], ["frames.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["observation_id"], ["ocr_observations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annotations_category_id"), "annotations", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_annotations_frame_id"), "annotations", ["frame_id"], unique=False)
    op.create_index(
        op.f("ix_annotations_observation_id"), "annotations", ["observation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_annotations_observation_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_frame_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_category_id"), table_name="annotations")
    op.drop_table("annotations")
    op.drop_index(op.f("ix_ocr_observations_sample_id"), table_name="ocr_observations")
    op.drop_table("ocr_observations")
    op.drop_index(op.f("ix_region_samples_region_id"), table_name="region_samples")
    op.drop_index(op.f("ix_region_samples_frame_id"), table_name="region_samples")
    op.drop_table("region_samples")
    op.drop_table("stage_checkpoints")
    op.drop_index(op.f("ix_frames_run_id"), table_name="frames")
    op.drop_table("frames")
    op.drop_index(op.f("ix_exports_run_id"), table_name="exports")
    op.drop_table("exports")
    op.drop_index(op.f("ix_pipeline_runs_video_id"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_profile_id"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_index(op.f("ix_hud_regions_profile_id"), table_name="hud_regions")
    op.drop_table("hud_regions")
    op.drop_index(op.f("ix_categories_profile_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_video_assets_project_id"), table_name="video_assets")
    op.drop_table("video_assets")
    op.drop_index(op.f("ix_game_profiles_project_id"), table_name="game_profiles")
    op.drop_table("game_profiles")
    op.drop_table("projects")
    # ### end Alembic commands ###
